import { Weapon } from "./types"

export const weapons: Weapon[] = [

  // =========================
  // ASSAULT RIFLES
  // =========================

  {
    id: "type-25",
    name: "Type 25",
    category: "Assault Rifle",
    image: "/weapons/ar/type-25.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "m16",
    name: "M16",
    category: "Assault Rifle",
    image: "/weapons/ar/m16.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "ak117",
    name: "AK117",
    category: "Assault Rifle",
    image: "/weapons/ar/ak117.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "ak47",
    name: "AK-47",
    category: "Assault Rifle",
    image: "/weapons/ar/ak47.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "asm10",
    name: "ASM10",
    category: "Assault Rifle",
    image: "/weapons/ar/asm10.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "m4",
    name: "M4",
    category: "Assault Rifle",
    image: "/weapons/ar/m4.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "bk57",
    name: "BK57",
    category: "Assault Rifle",
    image: "/weapons/ar/bk57.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "lk24",
    name: "LK24",
    category: "Assault Rifle",
    image: "/weapons/ar/lk24.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "icr-1",
    name: "ICR-1",
    category: "Assault Rifle",
    image: "/weapons/ar/icr-1.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "man-o-war",
    name: "Man-O-War",
    category: "Assault Rifle",
    image: "/weapons/ar/man-o-war.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "kn-44",
    name: "KN-44",
    category: "Assault Rifle",
    image: "/weapons/ar/kn-44.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "hbra3",
    name: "HBRa3",
    category: "Assault Rifle",
    image: "/weapons/ar/hbra3.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "hvk-30",
    name: "HVK-30",
    category: "Assault Rifle",
    image: "/weapons/ar/hvk-30.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "dr-h",
    name: "DR-H",
    category: "Assault Rifle",
    image: "/weapons/ar/dr-h.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "peacekeeper-mk2",
    name: "Peacekeeper MK2",
    category: "Assault Rifle",
    image: "/weapons/ar/peacekeeper-mk2.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "fr556",
    name: "FR.556",
    category: "Assault Rifle",
    image: "/weapons/ar/fr556.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "as-val",
    name: "AS VAL",
    category: "Assault Rifle",
    image: "/weapons/ar/as-val.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "cr56-amax",
    name: "CR-56 AMAX",
    category: "Assault Rifle",
    image: "/weapons/ar/cr56-amax.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "m13",
    name: "M13",
    category: "Assault Rifle",
    image: "/weapons/ar/m13.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "swordfish",
    name: "Swordfish",
    category: "Assault Rifle",
    image: "/weapons/ar/swordfish.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "kilo-141",
    name: "Kilo 141",
    category: "Assault Rifle",
    image: "/weapons/ar/kilo-141.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "oden",
    name: "Oden",
    category: "Assault Rifle",
    image: "/weapons/ar/oden.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "krig-6",
    name: "Krig 6",
    category: "Assault Rifle",
    image: "/weapons/ar/krig-6.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "em2",
    name: "EM2",
    category: "Assault Rifle",
    image: "/weapons/ar/em2.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "maddox",
    name: "Maddox",
    category: "Assault Rifle",
    image: "/weapons/ar/maddox.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "ffar-1",
    name: "FFAR 1",
    category: "Assault Rifle",
    image: "/weapons/ar/ffar-1.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "grau-556",
    name: "Grau 5.56",
    category: "Assault Rifle",
    image: "/weapons/ar/grau-556.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "groza",
    name: "Groza",
    category: "Assault Rifle",
    image: "/weapons/ar/groza.webp",
    eligibleSeasonalCamos: 36,
  },
{
    id: "type-19",
    name: "Type 19",
    category: "Assault Rifle",
    image: "/weapons/ar/type-19.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "bp50",
    name: "BP50",
    category: "Assault Rifle",
    image: "/weapons/ar/bp50.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "lag-53",
    name: "LAG 53",
    category: "Assault Rifle",
    image: "/weapons/ar/lag-53.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "xm4",
    name: "XM4",
    category: "Assault Rifle",
    image: "/weapons/ar/xm4.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "vargo-s",
    name: "Vargo-S",
    category: "Assault Rifle",
    image: "/weapons/ar/vargo-s.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "ram-7",
    name: "RAM-7",
    category: "Assault Rifle",
    image: "/weapons/ar/ram-7.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "lachmann-556",
    name: "Lachmann-556",
    category: "Assault Rifle",
    image: "/weapons/ar/lachmann-556.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "bal-27",
    name: "BAL-27",
    category: "Assault Rifle",
    image: "/weapons/ar/bal-27.webp",
    eligibleSeasonalCamos: 36,
  },

  // =========================
  // SNIPER RIFLES
  // =========================

  {
    id: "xpr-50",
    name: "XPR-50",
    category: "Sniper",
    image: "/weapons/sniper/xpr-50.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "arctic-50",
    name: "Arctic .50",
    category: "Sniper",
    image: "/weapons/sniper/arctic-50.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "m21-ebr",
    name: "M21 EBR",
    category: "Sniper",
    image: "/weapons/sniper/m21-ebr.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "dl-q33",
    name: "DL Q33",
    category: "Sniper",
    image: "/weapons/sniper/dl-q33.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "locus",
    name: "Locus",
    category: "Sniper",
    image: "/weapons/sniper/locus.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "na-45",
    name: "NA-45",
    category: "Sniper",
    image: "/weapons/sniper/na-45.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "outlaw",
    name: "Outlaw",
    category: "Sniper",
    image: "/weapons/sniper/outlaw.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "rytec-amr",
    name: "Rytec AMR",
    category: "Sniper",
    image: "/weapons/sniper/rytec-amr.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "svd",
    name: "SVD",
    category: "Sniper",
    image: "/weapons/sniper/svd.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "koshka",
    name: "Koshka",
    category: "Sniper",
    image: "/weapons/sniper/koshka.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "zrg-20mm",
    name: "ZRG 20mm",
    category: "Sniper",
    image: "/weapons/sniper/zrg-20mm.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "hdr",
    name: "HDR",
    category: "Sniper",
    image: "/weapons/sniper/hdr.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "lw3-tundra",
    name: "LW3-Tundra",
    category: "Sniper",
    image: "/weapons/sniper/lw3-tundra.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "3-line-rifle",
    name: "3-Line Rifle",
    category: "Sniper",
    image: "/weapons/sniper/3-line-rifle.webp",
    eligibleSeasonalCamos: 36,
  },

  // =========================
  // LIGHT MACHINE GUNS
  // =========================

  {
    id: "s36",
    name: "S36",
    category: "LMG",
    image: "/weapons/lmg/s36.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "ul736",
    name: "UL736",
    category: "LMG",
    image: "/weapons/lmg/ul736.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "rpd",
    name: "RPD",
    category: "LMG",
    image: "/weapons/lmg/rpd.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "m4lmg",
    name: "M4LMG",
    category: "LMG",
    image: "/weapons/lmg/m4lmg.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "chopper",
    name: "Chopper",
    category: "LMG",
    image: "/weapons/lmg/chopper.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "holger-26",
    name: "Holger 26",
    category: "LMG",
    image: "/weapons/lmg/holger-26.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "hades",
    name: "Hades",
    category: "LMG",
    image: "/weapons/lmg/hades.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "pkm",
    name: "PKM",
    category: "LMG",
    image: "/weapons/lmg/pkm.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "dingo",
    name: "Dingo",
    category: "LMG",
    image: "/weapons/lmg/dingo.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "bruen-mk9",
    name: "Bruen-MK9",
    category: "LMG",
    image: "/weapons/lmg/bruen-mk9.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "mg42",
    name: "MG42",
    category: "LMG",
    image: "/weapons/lmg/mg42.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "raal-mg",
    name: "RAAL MG",
    category: "LMG",
    image: "/weapons/lmg/raal-mg.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "mg-82",
    name: "MG 82",
    category: "LMG",
    image: "/weapons/lmg/mg-82.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "dp27",
    name: "DP27",
    category: "LMG",
    image: "/weapons/lmg/dp27.webp",
    eligibleSeasonalCamos: 36,
  },

  // =========================
  // SMGs
  // =========================

  {
    id: "rus-79u",
    name: "RUS-79U",
    category: "SMG",
    image: "/weapons/smg/rus-79u.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "chicom",
    name: "Chicom",
    category: "SMG",
    image: "/weapons/smg/chicom.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "pdw-57",
    name: "PDW-57",
    category: "SMG",
    image: "/weapons/smg/pdw-57.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "razorback",
    name: "Razorback",
    category: "SMG",
    image: "/weapons/smg/razorback.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "msmc",
    name: "MSMC",
    category: "SMG",
    image: "/weapons/smg/msmc.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "hg-40",
    name: "HG 40",
    category: "SMG",
    image: "/weapons/smg/hg-40.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "pharo",
    name: "Pharo",
    category: "SMG",
    image: "/weapons/smg/pharo.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "gks",
    name: "GKS",
    category: "SMG",
    image: "/weapons/smg/gks.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "cordite",
    name: "Cordite",
    category: "SMG",
    image: "/weapons/smg/cordite.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "qq9",
    name: "QQ9",
    category: "SMG",
    image: "/weapons/smg/qq9.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "fennec",
    name: "Fennec",
    category: "SMG",
    image: "/weapons/smg/fennec.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "agr-556",
    name: "AGR 556",
    category: "SMG",
    image: "/weapons/smg/agr-556.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "qxr",
    name: "QXR",
    category: "SMG",
    image: "/weapons/smg/qxr.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "pp19-bizon",
    name: "PP19 Bizon",
    category: "SMG",
    image: "/weapons/smg/pp19-bizon.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "mx9",
    name: "MX9",
    category: "SMG",
    image: "/weapons/smg/mx9.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "cbr4",
    name: "CBR4",
    category: "SMG",
    image: "/weapons/smg/cbr4.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "ppsh-41",
    name: "PPSh-41",
    category: "SMG",
    image: "/weapons/smg/ppsh-41.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "mac-10",
    name: "MAC-10",
    category: "SMG",
    image: "/weapons/smg/mac-10.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "ksp-45",
    name: "KSP 45",
    category: "SMG",
    image: "/weapons/smg/ksp-45.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "switchblade-x9",
    name: "Switchblade X9",
    category: "SMG",
    image: "/weapons/smg/switchblade-x9.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "lapa",
    name: "LAPA",
    category: "SMG",
    image: "/weapons/smg/lapa.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "ots-9",
    name: "OTs 9",
    category: "SMG",
    image: "/weapons/smg/ots-9.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "striker-45",
    name: "Striker 45",
    category: "SMG",
    image: "/weapons/smg/striker-45.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "cx-9",
    name: "CX-9",
    category: "SMG",
    image: "/weapons/smg/cx-9.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "tec-9",
    name: "TEC-9",
    category: "SMG",
    image: "/weapons/smg/tec-9.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "iso",
    name: "ISO",
    category: "SMG",
    image: "/weapons/smg/iso.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "uss-9",
    name: "USS 9",
    category: "SMG",
    image: "/weapons/smg/uss-9.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "vmp",
    name: "VMP",
    category: "SMG",
    image: "/weapons/smg/vmp.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "sten",
    name: "Sten",
    category: "SMG",
    image: "/weapons/smg/sten.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "lc10",
    name: "LC10",
    category: "SMG",
    image: "/weapons/smg/lc10.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "fss-hurricane",
    name: "FSS Hurricane",
    category: "SMG",
    image: "/weapons/smg/fss-hurricane.webp",
    eligibleSeasonalCamos: 36,
  },

  // =========================
  // SHOTGUNS
  // =========================

  {
    id: "hs2126",
    name: "HS2126",
    category: "Shotgun",
    image: "/weapons/shotgun/hs2126.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "by15",
    name: "BY15",
    category: "Shotgun",
    image: "/weapons/shotgun/by15.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "hs0405",
    name: "HS0405",
    category: "Shotgun",
    image: "/weapons/shotgun/hs0405.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "striker",
    name: "Striker",
    category: "Shotgun",
    image: "/weapons/shotgun/striker.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "krm-262",
    name: "KRM-262",
    category: "Shotgun",
    image: "/weapons/shotgun/krm-262.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "echo",
    name: "Echo",
    category: "Shotgun",
    image: "/weapons/shotgun/echo.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "r9-0",
    name: "R9-0",
    category: "Shotgun",
    image: "/weapons/shotgun/r9-0.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "jak-12",
    name: "JAK-12",
    category: "Shotgun",
    image: "/weapons/shotgun/jak-12.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "argus",
    name: "Argus",
    category: "Shotgun",
    image: "/weapons/shotgun/argus.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "vlk-rogue",
    name: "VLK Rogue",
    category: "Shotgun",
    image: "/weapons/shotgun/vlk-rogue.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "einhorn-revolving",
    name: "Einhorn Revolving",
    category: "Shotgun",
    image: "/weapons/shotgun/einhorn-revolving.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "mx-guardian",
    name: "MX-Guardian",
    category: "Shotgun",
    image: "/weapons/shotgun/mx-guardian.webp",
    eligibleSeasonalCamos: 36,
  },

  // =========================
  // MARKSMAN RIFLES
  // =========================

  {
    id: "kilo-bolt-action",
    name: "Kilo Bolt-Action",
    category: "Marksman",
    image: "/weapons/marksman/kilo-bolt-action.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "sks",
    name: "SKS",
    category: "Marksman",
    image: "/weapons/marksman/sks.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "sp-r-208",
    name: "SP-R 208",
    category: "Marksman",
    image: "/weapons/marksman/sp-r-208.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "mk2",
    name: "MK2",
    category: "Marksman",
    image: "/weapons/marksman/mk2.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "type-63",
    name: "Type 63",
    category: "Marksman",
    image: "/weapons/marksman/type-63.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "m1-garand",
    name: "M1 Garand",
    category: "Marksman",
    image: "/weapons/marksman/m1-garand.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "so-14",
    name: "SO-14",
    category: "Marksman",
    image: "/weapons/marksman/so-14.webp",
    eligibleSeasonalCamos: 36,
  },

  // =========================
  // PISTOLS
  // =========================

  {
    id: "j358",
    name: "J358",
    category: "Pistol",
    image: "/weapons/pistol/j358.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "mw11",
    name: "MW11",
    category: "Pistol",
    image: "/weapons/pistol/mw11.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "50-gs",
    name: ".50 GS",
    category: "Pistol",
    image: "/weapons/pistol/50-gs.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "renetti",
    name: "Renetti",
    category: "Pistol",
    image: "/weapons/pistol/renetti.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "shorty",
    name: "Shorty",
    category: "Pistol",
    image: "/weapons/pistol/shorty.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "crossbow",
    name: "Crossbow",
    category: "Pistol",
    image: "/weapons/pistol/crossbow.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "l-car-9",
    name: "L-CAR 9",
    category: "Pistol",
    image: "/weapons/pistol/l-car-9.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "dobvra",
    name: "Dobvra",
    category: "Pistol",
    image: "/weapons/pistol/dobvra.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "nail-gun",
    name: "Nail Gun",
    category: "Pistol",
    image: "/weapons/pistol/nail-gun.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "machine-pistol",
    name: "Machine Pistol",
    category: "Pistol",
    image: "/weapons/pistol/machine-pistol.webp",
    eligibleSeasonalCamos: 36,
  },

  // =========================
  // MELEES
  // =========================

  {
    id: "knife",
    name: "Knife",
    category: "Melee",
    image: "/weapons/melee/knife.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "axe",
    name: "Axe",
    category: "Melee",
    image: "/weapons/melee/axe.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "shovel",
    name: "Shovel",
    category: "Melee",
    image: "/weapons/melee/shovel.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "baseball-bat",
    name: "Baseball Bat",
    category: "Melee",
    image: "/weapons/melee/baseball-bat.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "Nunchucks",
    name: "Nunchucks",
    category: "Melee",
    image: "/weapons/melee/nunchucks.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "katana",
    name: "Katana",
    category: "Melee",
    image: "/weapons/melee/katana.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "prizefighters",
    name: "Prizefighters",
    category: "Melee",
    image: "/weapons/melee/prizefighters.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "wrench",
    name: "Wrench",
    category: "Melee",
    image: "/weapons/melee/wrench.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "sickle",
    name: "Sickle",
    category: "Melee",
    image: "/weapons/melee/sickle.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "machete",
    name: "Machete",
    category: "Melee",
    image: "/weapons/melee/machete.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "kali-sticks",
    name: "Kali Sticks",
    category: "Melee",
    image: "/weapons/melee/kali-sticks.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "butterfly-knife",
    name: "Butterfly Knife",
    category: "Melee",
    image: "/weapons/melee/butterfly-knife.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "sai",
    name: "Sai",
    category: "Melee",
    image: "/weapons/melee/sai.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "ballistic-knife",
    name: "Ballistic Knife",
    category: "Melee",
    image: "/weapons/melee/ballistic-knife.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "spear",
    name: "Spear",
    category: "Melee",
    image: "/weapons/melee/spear.webp",
    eligibleSeasonalCamos: 36,
  },
  
  // =========================
  // LAUNCHERS
  // =========================

  {
    id: "fhj-18",
    name: "FHJ-18",
    category: "Launcher",
    image: "/weapons/launcher/fhj-18.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "smrs",
    name: "SMRS",
    category: "Launcher",
    image: "/weapons/launcher/smrs.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "thumper",
    name: "Thumper",
    category: "Launcher",
    image: "/weapons/launcher/thumper.webp",
    eligibleSeasonalCamos: 36,
  },
  {
    id: "d13-sector",
    name: "D13 Sector",
    category: "Launcher",
    image: "/weapons/launcher/d13-sector.webp",
    eligibleSeasonalCamos: 36,
  },
]